version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/universal:2
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    depends_on:
      - db
    postCreateCommand: "sudo apt-get update && sudo apt-get install -y php php-mysql"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "biblioteca_db"
    volumes:
      - mysql-data:/var/lib/mysql
      # Esto carga tu archivo SQL automáticamente al iniciar:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: